### ISSUE TITLE
Question about CloudForms / Foreman integration

### ISSUE THREAD

**Issue by b-long** [cbolz/ManageIQ#2]
Hi there and thanks for providing this great resource!

I'm curious about the [foreman integration](https://github.com/cbolz/ManageIQ/tree/3e284462b95883e3ac1e10b70efd933bb7d896c0/register_foreman) you're providing.  If one is paying for CloudForms, is there any additional cost to integrating foreman?

**Comment by cbolz** [comment]
HiHo,
there is no additional cost when you extend CloudForms by adding custom methods. You can choose to use the community project of the Foreman or you could acquire a subscription of Red Hat Satellite, which is based on Foreman and other community projects, but gives you access to the Red Hat Support for opening tickets or support requests.

The code I provide here on Github is not part of Red Hat CloudForms and therefore not officially supported by Red Hat.

Further information which might be helpful:
https://access.redhat.com/support/policy/updates/cloudforms/
http://www.jung-christian.de/post/2017/01/manageiq-vs-cloudforms/
https://www.redhat.com/en/technologies/management/satellite

Hope this helps,
Christian
